version: '3.8'
networks:
  mc_app:
    external: false
    name: mc_app

services:
  db:
    container_name: mc_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Naren
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: manage_contacts
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  web:
    build: .
    container_name: mc_web
    restart: always
    ports:
      - "3000:80"